### PR TITLE
Support for full api

### PR DESCRIPTION
**Pull request by tomatohater**

### CODE REVIEW

**Comment by cgoldberg** [comment]
thanks for the PR!
I'd prefer not to introduce any external dependencies (six and requests).  could you revert those parts in your sauceclient.py?

**Comment by tomatohater** [comment]
I felt these common external libs are preferable to wacky "if PY2" conditionals. But fair enough. I'll revert those back tonight. :)

Drew

**Comment by tomatohater** [comment]
Code has been updated with no external dependencies. I didn't use any PY2 conditionals, just catching import errors for the two modules that changed location in Py3.

**Comment by cgoldberg** [comment]
thanks.
I just merged it as-is.  If you are up for it, the documentation in README.rst needs to be updated to reflect these changes.

**Comment by tomatohater** [comment]
Cool. As long as you're good with the code, I'll go update to docs in the next day or two.

Also, I had updated the version to 0.3dev... Wasn't sure what you wanted to go with once this gets packaged up.

**Pull request merged**
